version: '3.8'

services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-api
    restart: always
    ports:
      - 3000:3000
    environment:
      - PORT=3000
      - DATABASE_URL=mysql://root:1234@mysql_db:3306/nestdb
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./package.json:/app/package.json
      - ./yarn.lock:/app/yarn.lock
      - /app/node_modules
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:9.0
    command: --lower_case_table_names=1
    container_name: mysqlprisma
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=nestdb
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h127.0.0.1', '-P3306']
      interval: 5s
      timeout: 2s
      retries: 20

volumes:
  mysql:
    name: nest-prisma-docker-db
