version: '3'

services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nest-api
    restart: always
    ports:
      - 3001:3001
    env_file:
      - .env
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:8.0
    container_name: mysqlprisma
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=nestdb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  backup:
    image: mysql:8.0
    container_name: backup-mysql
    restart: always
    command: sh -c "mysqldump -u root -p1234 nestdb > /backup/backup.sql"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backup:/backup

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
