FROM node:21 AS builder

WORKDIR /app

COPY package* .
COPY prisma ./prisma

RUN npm install

COPY . .

RUN npm run build

FROM node:21

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package* ./
COPY --from=builder /app/dist ./dist

ENV NODE_ENV=production

EXPOSE 3001

CMD [ "npm", "run", "start:prod" ]